<?php

/**
 * @file
 * Views table search Views module help and theme functions.
 */

// Preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('views_tablesearch', 'inc', 'views_tablesearch.theme');

/**
 * Implements hook_theme().
 */
function views_views_tablesearch_theme($existing, $type, $theme, $path) {
  return [
    'tablesearch' => [
      'file' => 'views_tablesearch.theme.inc',
    ],
  ];
}
